# Generated by Django 6.0.6 on 2026-07-04 11:18

import django.db.models.deletion
from django.db import migrations, models

import algorithms.models.algorithm


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('general_description', models.TextField(default='General description will be added soon.')),
                ('input_description', models.JSONField(default=algorithms.models.algorithm._default_input_description)),
                ('output_description', models.TextField(default='Output description will be added soon.')),
                ('code', models.JSONField(default=list)),
                ('categories', models.ManyToManyField(related_name='algorithms', to='algorithms.category')),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='algorithms',
                                                 to='algorithms.difficulty')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.JSONField(default=dict)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases',
                                                to='algorithms.algorithm')),
            ],
            options={
                'ordering': ['-algorithm__created_at', 'id'],
            },
        ),
    ]
