# Generated by Django 5.2.4 on 2025-07-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("algorithms", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testcase",
            options={"ordering": ["-algorithm__created", "id"]},
        ),
        migrations.AlterField(
            model_name="algorithm",
            name="code",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="body",
            field=models.JSONField(),
        ),
    ]
