# Generated by Django 5.2.4 on 2025-08-05 13:38

import algorithms.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("algorithms", "0002_alter_testcase_options_alter_algorithm_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="algorithm",
            name="description",
        ),
        migrations.AddField(
            model_name="algorithm",
            name="general_description",
            field=models.TextField(default="General description will be added soon."),
        ),
        migrations.AddField(
            model_name="algorithm",
            name="input_description",
            field=models.JSONField(default=algorithms.models.default_input_description),
        ),
        migrations.AddField(
            model_name="algorithm",
            name="output_description",
            field=models.TextField(default="Output description will be added soon."),
        ),
    ]
