# Generated by Django 5.2.5 on 2025-09-23 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("algorithms", "0003_comment_likes_delete_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="algorithms.comment",
            ),
        ),
    ]
