# Generated by Django 5.2.5 on 2025-08-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("algorithms", "0003_remove_algorithm_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="algorithm",
            name="slug",
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="difficulty",
            name="slug",
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
